= Caddy Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Asciidoctor_: https://asciidoctor.org/[Asciidoctor]
:Caddy: https://caddyserver.com/[Caddy]
:Fedora-IoT: https://getfedora.org/en/iot/[Fedora IoT]
:Podman: https://podman.io/[Podman]
:pre-commit: https://pre-commit.com/[pre-commit]

image:https://github.com/jwillikers/caddy-config/actions/workflows/ci.yml/badge.svg[GitHub Workflow Status]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

{Caddy} configuration files for services on running on my various devices.

== Synopsis

These instructions are for using this Caddyfile and Caddy container using rootless {Podman} on {Fedora-IoT}.
The instructions for building will assume that you are on Fedora.

== Usage

. Clone the repository.
+
[,sh]
----
git clone git@github.com:jwillikers/caddy-config.git
----

. Change into the project directory.
+
[,sh]
----
cd caddy-config
----

. Symlink sites from the `sites-available` subdirectory to the `sites-available` subdirectory to enable them.
+
[,sh]
----
ln --relative --symbolic sites-available/nextcloud.caddyfile sites-enabled/nextcloud.caddyfile
----

. Follow the instructions for setting up and running the https://github.com/jwillikers/caddy-ovh-image[Caddy OVH Image] using the Caddyfile provided in this repository.

== Develop

. Install the pre-commit in the toolbox.
+
[,sh]
----
sudo dnf -y install pre-commit
----

. Install pre-commit's Git hooks.
+
[,sh]
----
pre-commit install
----

. Format the Caddyfile.
+
[,sh]
----
podman run \
  -it \
  --name caddy-fmt \
  --rm \
  --volume $PWD:/srv:Z \
  docker.io/caddy:latest caddy fmt --overwrite
----

. Validate the Caddyfile.
+
[,sh]
----
podman run \
  -it \
  --name caddy-validate \
  --rm \
  --volume $PWD:/srv:Z \
  quay.io/jwillikers/caddy-ovh:latest caddy validate
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* {Asciidoctor_}
* {Caddy}
* {Fedora-IoT}
* {fish}
* {Podman}
* {pre-commit}

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is provided in the link:LICENSE.adoc[license file].

© 2022-2023 Jordan Williams

== Authors

mailto:{email}[{author}]
