---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
    steps:
      - uses: actions/checkout@v2
      - name: Check Caddyfile formatting
        run: podman run -it --rm --volume $PWD/Caddyfile:/srv/Caddyfile:Z docker.io/caddy:latest caddy fmt --overwrite
      - name: Validate Caddyfile
        run: podman run -it --rm --volume $PWD/Caddyfile:/srv/Caddyfile:Z quay.io/jwillikers/caddy-cloudflare:latest caddy validate
