---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3.8
        with:
          version: "0.80"
      - name: Check formatting of the Caddyfiles
        shell: nu {0}
        run: |
          for file in (glob "sites-available/*.caddyfile") {
            ^podman run -it --rm --volume $"(pwd):/srv:Z" docker.io/caddy:latest caddy fmt $"sites-available/($file | path basename)"
          }
      - name: Validate the Caddyfiles
        shell: nu {0}
        run: |
          for file in (glob "sites-available/*.caddyfile") {
            ^ln --relative --symbolic $file $"sites-enabled/($file | path basename)"
          }
          ^podman run -it --rm --volume $"(pwd):/srv:Z" quay.io/jwillikers/caddy-ovh:latest caddy validate
